/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

/**
 *
 * @author Jaime-PC
 */
public class VentanaCalculadora extends javax.swing.JFrame {
    
    //aui van las variables de instancia
    double operando1 =0; //almacena el primer numero
    String operacion=""; //alamcena la operacion que se ha pulsado
    

    /**
     * Creates new form VentanaCalculadora
     */
    public VentanaCalculadora() {
        initComponents();
    } 
    public void escribeNumeroEnLaPantalla(String numero){
        if(display.getText()=="0"){
        display.setText(numero);
    }
        else{
            display.setText(display.getText()+numero);
        }
    }
    //la funcion que se encarga de trabjaar con la operacion pulsada
    public void operacionPulsada(String _operacion){
        //guardado el valor de la pantalla en la variable operando1
        operando1 = Double.valueOf(display.getText());
        
        //pongo a cero la pantalla
        display.setText("0");
        //guardo la operacion que he pulsado
        operacion= _operacion;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        display = new javax.swing.JLabel();
        boton7 = new javax.swing.JButton();
        boton9 = new javax.swing.JButton();
        boton4 = new javax.swing.JButton();
        boton5 = new javax.swing.JButton();
        BotonMultiplicar = new javax.swing.JButton();
        botonDividir = new javax.swing.JButton();
        boton8 = new javax.swing.JButton();
        boton6 = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();
        boton1 = new javax.swing.JButton();
        boton3 = new javax.swing.JButton();
        boton0 = new javax.swing.JButton();
        BotonResta = new javax.swing.JButton();
        BotonIgual = new javax.swing.JButton();
        BotonSuma = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        display.setBackground(new java.awt.Color(0, 0, 0));
        display.setFont(new java.awt.Font("Stencil", 0, 48)); // NOI18N
        display.setForeground(new java.awt.Color(0, 255, 0));
        display.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        display.setText("0");
        display.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        display.setOpaque(true);

        boton7.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton7.setText("7");
        boton7.setMaximumSize(new java.awt.Dimension(73, 73));
        boton7.setMinimumSize(new java.awt.Dimension(73, 73));
        boton7.setPreferredSize(new java.awt.Dimension(73, 73));
        boton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton7ActionPerformed(evt);
            }
        });

        boton9.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton9.setText("9");
        boton9.setMaximumSize(new java.awt.Dimension(73, 73));
        boton9.setMinimumSize(new java.awt.Dimension(73, 73));
        boton9.setPreferredSize(new java.awt.Dimension(73, 73));
        boton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton9ActionPerformed(evt);
            }
        });

        boton4.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton4.setText("4");
        boton4.setMaximumSize(new java.awt.Dimension(73, 73));
        boton4.setMinimumSize(new java.awt.Dimension(73, 73));
        boton4.setPreferredSize(new java.awt.Dimension(73, 73));
        boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton4ActionPerformed(evt);
            }
        });

        boton5.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton5.setText("5");
        boton5.setMaximumSize(new java.awt.Dimension(73, 73));
        boton5.setMinimumSize(new java.awt.Dimension(73, 73));
        boton5.setPreferredSize(new java.awt.Dimension(73, 73));
        boton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton5ActionPerformed(evt);
            }
        });

        BotonMultiplicar.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        BotonMultiplicar.setText("*");
        BotonMultiplicar.setMaximumSize(new java.awt.Dimension(73, 73));
        BotonMultiplicar.setMinimumSize(new java.awt.Dimension(73, 73));
        BotonMultiplicar.setPreferredSize(new java.awt.Dimension(73, 73));
        BotonMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMultiplicarActionPerformed(evt);
            }
        });

        botonDividir.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        botonDividir.setText("/");
        botonDividir.setMaximumSize(new java.awt.Dimension(73, 73));
        botonDividir.setMinimumSize(new java.awt.Dimension(73, 73));
        botonDividir.setPreferredSize(new java.awt.Dimension(73, 73));
        botonDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDividirActionPerformed(evt);
            }
        });

        boton8.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton8.setText("8");
        boton8.setMaximumSize(new java.awt.Dimension(73, 73));
        boton8.setMinimumSize(new java.awt.Dimension(73, 73));
        boton8.setPreferredSize(new java.awt.Dimension(73, 73));
        boton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton8ActionPerformed(evt);
            }
        });

        boton6.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton6.setText("6");
        boton6.setMaximumSize(new java.awt.Dimension(73, 73));
        boton6.setMinimumSize(new java.awt.Dimension(73, 73));
        boton6.setPreferredSize(new java.awt.Dimension(73, 73));
        boton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton6ActionPerformed(evt);
            }
        });

        boton2.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton2.setText("2");
        boton2.setMaximumSize(new java.awt.Dimension(73, 73));
        boton2.setMinimumSize(new java.awt.Dimension(73, 73));
        boton2.setPreferredSize(new java.awt.Dimension(73, 73));
        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });

        boton1.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton1.setText("1");
        boton1.setMaximumSize(new java.awt.Dimension(73, 73));
        boton1.setMinimumSize(new java.awt.Dimension(73, 73));
        boton1.setPreferredSize(new java.awt.Dimension(73, 73));
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });

        boton3.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton3.setText("3");
        boton3.setMaximumSize(new java.awt.Dimension(73, 73));
        boton3.setMinimumSize(new java.awt.Dimension(73, 73));
        boton3.setPreferredSize(new java.awt.Dimension(73, 73));
        boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton3ActionPerformed(evt);
            }
        });

        boton0.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        boton0.setText("0");
        boton0.setMaximumSize(new java.awt.Dimension(73, 73));
        boton0.setMinimumSize(new java.awt.Dimension(73, 73));
        boton0.setPreferredSize(new java.awt.Dimension(73, 73));
        boton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton0ActionPerformed(evt);
            }
        });

        BotonResta.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        BotonResta.setText("-");
        BotonResta.setMaximumSize(new java.awt.Dimension(73, 73));
        BotonResta.setMinimumSize(new java.awt.Dimension(73, 73));
        BotonResta.setPreferredSize(new java.awt.Dimension(73, 73));
        BotonResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRestaActionPerformed(evt);
            }
        });

        BotonIgual.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        BotonIgual.setText("=");
        BotonIgual.setMaximumSize(new java.awt.Dimension(73, 73));
        BotonIgual.setMinimumSize(new java.awt.Dimension(73, 73));
        BotonIgual.setPreferredSize(new java.awt.Dimension(73, 73));
        BotonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIgualActionPerformed(evt);
            }
        });

        BotonSuma.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        BotonSuma.setText("+");
        BotonSuma.setMaximumSize(new java.awt.Dimension(73, 73));
        BotonSuma.setMinimumSize(new java.awt.Dimension(73, 73));
        BotonSuma.setPreferredSize(new java.awt.Dimension(73, 73));
        BotonSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSumaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(display, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(boton7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boton8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(boton9, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                        .addComponent(boton0, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(boton5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(boton6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BotonSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BotonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonResta, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton9, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonResta, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonSuma, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton0, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton7ActionPerformed
      escribeNumeroEnLaPantalla("7");
    }//GEN-LAST:event_boton7ActionPerformed

    private void boton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton0ActionPerformed
        escribeNumeroEnLaPantalla("0");
    }//GEN-LAST:event_boton0ActionPerformed

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
       escribeNumeroEnLaPantalla("1");
    }//GEN-LAST:event_boton1ActionPerformed

    private void boton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton5ActionPerformed
         escribeNumeroEnLaPantalla("5");
    }//GEN-LAST:event_boton5ActionPerformed

    private void boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton4ActionPerformed
        escribeNumeroEnLaPantalla("4");
    }//GEN-LAST:event_boton4ActionPerformed

    private void boton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton8ActionPerformed
       escribeNumeroEnLaPantalla("8");
    }//GEN-LAST:event_boton8ActionPerformed

    private void boton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton9ActionPerformed
        escribeNumeroEnLaPantalla("9");
    }//GEN-LAST:event_boton9ActionPerformed

    private void boton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton6ActionPerformed
        escribeNumeroEnLaPantalla("6");
    }//GEN-LAST:event_boton6ActionPerformed

    private void botonDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDividirActionPerformed
         operacionPulsada("/");
    }//GEN-LAST:event_botonDividirActionPerformed

    private void BotonMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMultiplicarActionPerformed
         operacionPulsada("*");
    }//GEN-LAST:event_BotonMultiplicarActionPerformed

    private void BotonRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRestaActionPerformed
         operacionPulsada("-");
    }//GEN-LAST:event_BotonRestaActionPerformed

    private void BotonSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSumaActionPerformed
         operacionPulsada("+");
    }//GEN-LAST:event_BotonSumaActionPerformed

    private void BotonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIgualActionPerformed
       //el boton igual tiene saber que operacion se pulso
       //como ese valor lo guarde en la variable operaacion
       //monto un if para que dependiendo del valor se realice ç
       //la operacion+
       double operando2 =Double.valueOf(display.getText());
        //si la operacion era la suma:
        if(operacion.equals("+")){
            operando1= operando1 + operando2;
        
         //si la operacion era resta
         if(operacion.equals("-")){
            operando1 = operando1 - operando2;
         }
         //si la operacion es multiplicaion
         if(operacion.equals("*")){
             operando1 =operando1 * operando2;
         }
         //si la operacion era division
         if(operacion.equals("/")){
             operando1 = operando1 / operando2;
         }
         
        }
        //por ultimo,muestro el resultado por pantall
        display.setText(String.valueOf(operando1));
    }//GEN-LAST:event_BotonIgualActionPerformed

    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed
         escribeNumeroEnLaPantalla("2");
    }//GEN-LAST:event_boton2ActionPerformed

    private void boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton3ActionPerformed
         escribeNumeroEnLaPantalla("3");
    }//GEN-LAST:event_boton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonIgual;
    private javax.swing.JButton BotonMultiplicar;
    private javax.swing.JButton BotonResta;
    private javax.swing.JButton BotonSuma;
    private javax.swing.JButton boton0;
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    private javax.swing.JButton boton3;
    private javax.swing.JButton boton4;
    private javax.swing.JButton boton5;
    private javax.swing.JButton boton6;
    private javax.swing.JButton boton7;
    private javax.swing.JButton boton8;
    private javax.swing.JButton boton9;
    private javax.swing.JButton botonDividir;
    private javax.swing.JLabel display;
    // End of variables declaration//GEN-END:variables
}
